language: node_js
node_js:
  - 6.9.5
before_script:
  - npm install -g bower
  - bower install
script: 
 - phantomjs --version
 - phantomjs --web-security=false samples/test.js
 - node src/backend.js -r http://127.0.0.1/testsuite --serve-http ./ -b phantomjs --timeout 300 http://127.0.0.1/dist/
 - node src/backend.js -r http://127.0.0.1/testsuite/multiwindow --serve-http ./ -b phantomjs http://127.0.0.1/dist/
 - bash -c "! node src/backend.js -r http://127.0.0.1/testsuite/failing --serve-http ./ -b phantomjs http://127.0.0.1/dist/"