language: node_js
node_js:
  - 6.9.5
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - "export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
before_script:
  - npm install -g bower
  - bower install
  - npm install
script: 
 - phantomjs --version
 - phantomjs --web-security=false samples/test.js
 - node src/backend.js -r http://127.0.0.1/testsuite --serve-http ./ -b phantomjs --timeout 300 http://127.0.0.1/dist/
 - node src/backend.js -r http://127.0.0.1/testsuite/multiwindow --serve-http ./ -b phantomjs http://127.0.0.1/dist/
 - bash -c "! node src/backend.js -r http://127.0.0.1/testsuite/failing --serve-http ./ -b phantomjs http://127.0.0.1/dist/"
 - node src/backend.js -r https://127.0.0.1/testsuite --serve-http ./ -b phantomjs --timeout 300 --https https://127.0.0.1/dist/
 - node src/backend.js -r http://127.0.0.1/playground --serve-http ./ --browser phantomjs --timeout=300  http://127.0.0.1/dist/
 - node src/backend.js -r http://127.0.0.1/tutorial --serve-http ./ --browser phantomjs --timeout=300  http://127.0.0.1/dist/
