#!/bin/bash
echo "(function(){" > inject.min.js
echo "" >> inject.min.js
cat inject.js >> inject.min.js
cat helpers/* >> inject.min.js
echo "" >> inject.min.js
echo "" >> inject.min.js

echo "}).call({cartFillerConfiguration:{},cartFillerEval:this.cartFillerEval});" >> inject.min.js
